general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.config/dotfiles-resources/tuscany-pixel-art.jpg
    blur_passes = 3
}

input-field {
    monitor =
    size = 18%, 4%
    outline_thickness = 2

    dots_size = 0.3
    dots_spacing = 0.3

    outer_color = rgba(deb1ffff) rgba(9b8bf8ff) 45deg
    inner_color = rgba(2c2a3a33)
    font_color = rgba(efefffaa)
    font_family = Monospace

    fade_on_empty = false
    rounding = 10
    placeholder_text =

    fail_text = $PAMFAIL

    check_color = rgba(4f4d6433)
    fail_color = rgba(deb1ffff) rgba(9b8bf8ff) 45deg

    shadow_passes = 1
    shadow_size = 2
    shadow_color = rgba(010316ff)
}

