# Disable the splash message
splash = false

# Load the wallpaper
preload = ~/dotfiles/resources/tuscany-pixel-art.jpg

# Default monitor
wallpaper {
    monitor =
    path = ~/dotfiles/resources/tuscany-pixel-art.jpg
}
