# Disable the splash message
splash = false

# Load the wallpaper
preload = ~/.config/dotfiles-resources/tuscany-pixel-art.jpg

# Default monitor
wallpaper {
    monitor =
    path = ~/.config/dotfiles-resources/tuscany-pixel-art.jpg
}
