general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 2
    on-timeout = notify-send "goodbye"
    on-resume = notify-send "hello"
    # on-timeout = brightnessctl -s set 10
    # on-resume = brightnessctl -r
}
