################
### MONITORS ###
################

source = ./hyprland-monitors.conf

#################
### AUTOSTART ###
#################

exec-once = hyprpaper
exec-once = waybar

exec-once = kitty -e bash -c "tmux attach || tmux new"

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE, 24
env = HYPRCURSOR_SIZE, 24

#####################
### LOOK AND FEEL ###
#####################

general {
    border_size = 2
    gaps_in = 5
    gaps_out = 10

    col.inactive_border = rgba(44415aff)
    col.active_border = rgba(deb1ffff) rgba(9b8bf8ff) 45deg
}

decoration {
    rounding = 10

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(010316ff)
    }

    # inactive_opacity = 0.8
    # blur {
    #     enabled = true
    #     size = 3
    #     passes = 1
    #     vibrancy = 0.1696
    # }
}

animations {
    enabled = off;

    # bezier = overshoot, 0.05, 1.15, 0.5, 1.01
    # animation = windows, 1, 4, overshoot
    # animation = workspaces, 1, 4, overshoot
    # animation = fade, 1, 7, default
    # animation = border, 1, 10, default
    # animation = borderangle, 1, 8, default
}

input {
    kb_options = ctrl:nocaps
    sensitivity = -0.4
    follow_mouse = 1
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    background_color = rgba(010316ff)
}

cursor {
    no_hardware_cursors = 1
    inactive_timeout = 3
    hide_on_key_press = true
    hide_on_touch = true
    hide_on_tablet = true
}

####################
### KEYBINDINGSS ###
####################

# Utilities
bind = CTRL ALT, delete, exit, # exit hyprland
bind = ALT, c, killactive, # close program in active window
bind = ALT SHIFT, c, forcekillactive, # force kill program in active window
bind = ALT, f, fullscreen, toggle
bind = ALT SHIFT, f, togglefloating

# Programs
bind = ALT, t, exec, kitty -e bash -c "tmux attach || tmux new"
bind = ALT, r, exec, wofi --show drun
bind = ALT, w, exec, firefox

# Move focus with hjkl
bind = ALT, h, movefocus, l
bind = ALT, j, movefocus, d
bind = ALT, k, movefocus, u
bind = ALT, l, movefocus, r

# Switch workspaces
bind = ALT, u, workspace, 1
bind = ALT, i, workspace, 2
bind = ALT, o, workspace, 3
bind = ALT, p, workspace, 4
bind = ALT SHIFT, u, workspace, 5
bind = ALT SHIFT, i, workspace, 6
bind = ALT SHIFT, o, workspace, 7
bind = ALT SHIFT, p, workspace, 8

# Move active window hjkl
bind = SUPER, h, movewindow, l
bind = SUPER, j, movewindow, d
bind = SUPER, k, movewindow, u
bind = SUPER, l, movewindow, r

# Move active window to a workspace
bind = SUPER, u, movetoworkspace, 1
bind = SUPER, i, movetoworkspace, 2
bind = SUPER, o, movetoworkspace, 3
bind = SUPER, p, movetoworkspace, 4
bind = SUPER SHIFT, u, movetoworkspace, 5
bind = SUPER SHIFT, i, movetoworkspace, 6
bind = SUPER SHIFT, o, movetoworkspace, 7
bind = SUPER SHIFT, p, movetoworkspace, 8

# Move/resize windows with mouse buttons and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = , XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

